version: '2.2'
services:

  dind:
    image: docker:dind
    hostname: dind
    environment:
      #DOCKER_TLS_CERTDIR: /certs
      DOCKER_TLS_CERTDIR: "" #desabilitando o TLS
    command: --insecure-registry gitlab:5005 #config o registry do gitlab como inseguro http
    volumes:
     - ./conf/dind/certs:/certs
    privileged: true
    links:
     - gitlab

  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "gitlab"
        gitlab_rails['registry_port'] = "5005"
        gitlab_rails['registry_path'] = "/var/opt/gitlab/gitlab-rails/shared/registry"
        registry_external_url 'http://gitlab:5005'
    ports:
     - "8081:80"
     - "65005:5005"
    mem_limit: 4096M
    #cpus: 4
     
  runner:
    image: gitlab/gitlab-runner
    depends_on:
      - gitlab
    #mem_limit: 4096M # caso queira limitar o uso de ram
    #cpus: 2048 # caso queira limitar o uso de cpus
    environment:
     # TLS Ligado
     #- DOCKER_HOST=tcp://dind:2376
     #- DOCKER_TLS_CERTDIR=/certs
     #- DOCKER_TLS_VERIFY=1
     # TLS desligado
     - DOCKER_HOST=tcp://dind:2375
    volumes:
     - ./conf/runner:/etc/gitlab-runner
     #- ./conf/dind/certs/client:/certs/client:ro
    links:
     - dind
     - gitlab